/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f114d0df-841f-4fc8-839c-c23ea979feb8",
    "aws_cognito_region": "us-east-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "5d91ff0b6c76420abce84c4872b768b5",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
